version: "3"
services:
  bia:
    image: bia:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIA_API_URL: http://bia-dev-elb.us-east-1.elasticbeanstalk.com
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: fvXCEGk8I0JPRYBJcn2m
      DB: bia
      DB_HOST: bia.cxq8wks8qvdp.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
