version: "3.4"

services:
  server:
    image: bia-local:latest
    ports:
      - 3001:8080
    links:
      - database
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIA_API_URL: http://localhost:3001
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB=bia
      - DB_HOST=database
      - DB_PORT=5432
  database:
     image: postgres:latest
     container_name: database
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=bia
     ports:
       - "5433:5432"
     restart: always
     volumes:
       - db:/var/lib/postgresql/data

volumes:
  db:
    