name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2
    
    # 2. Setar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 3. Logar no Docker Hub ou AWS ECR
    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 676206946905.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    
    # 4. Build da imagem Docker
    - name: Build Docker image
      run: |
        docker build -t meu-registro-ecr:latest .
    
    # 5. Fazer Push para o ECR
    - name: Push to ECR
      run: |
        docker tag bia:latest 676206946905.dkr.ecr.us-est-1.amazonaws.com/bia:latest
        docker push 676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest
    
    # 6. Atualizar o ECS com a nova imagem (Deploy)
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment --region ${{ secrets.AWS_REGION }}
