name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t myapp .
        docker tag myapp:latest 676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 676206946905.dkr.ecr.uus-east-1.amazonaws.com/bia:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        aws-region: <region>

    - name: Deploy to ECS
      run: |
        ecs-cli configure --cluster my-cluster --region us-east-1 --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ecs-cli compose --file docker-compose.yml --project-name myapp up
