name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 211125447912.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t myapp .
        docker tag myapp:latest 676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push 676206946905.dkr.ecr.uus-east-1.amazonaws.com/bia:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Deploy to ECS
      run: |
        ecs-cli configure --cluster ${{ secrets.ECS_CLUSTER }} --region us-east-1 --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ecs-cli compose --file docker-compose.yml --project-name myapp up
