name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    # 1. Checar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2
    
    # 2. Setar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        
    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 676206946905.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    
    # 4. Build da imagem Docker
    - name: Build Docker image
      run: |
        docker build -t 676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest .
    
    # 5. Fazer Push para o ECR
    - name: Push to ECR
      run: |
        docker tag 676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest 676206946905.dkr.ecr.east-1.amazonaws.com/676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest
        docker push 676206946905.dkr.ecr.us-east-1.amazonaws.com/676206946905.dkr.ecr.us-east-1.amazonaws.com/bia:latest
    
    # 6. Atualizar o ECS com a nova imagem (Deploy)
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster cluster-bia-ci_cd --service service-bia-ci-cd --force-new-deployment
